sudo: false
language: go
go:
  - 1.5.1
os:
  - linux
before_script:
  - git clone git://github.com/urisavka/blog.git blog
  - git clone git://github.com/urisavka/urisavka.github.io.git urisavka.github.io
  - ln -s `pwd`/urisavka.github.io `pwd`/blog/public
script:
  - cd blog
  - hugo -t hugo-cactus-theme
  - cd ..
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && rev=$(git rev-parse --short HEAD)
  - cd urisavka.github.io
  - git config user.email "urisavka@gmail.com"
  - git config user.name "Yurii Savka"
  - git pull origin master
  - git remote rm origin
  - git remote add origin "https://$GH_TOKEN@github.com/urisavka/urisavka.github.io.git"
  - git add --all
  - git commit -m "rebuild pages at ${rev}"
  - git push origin master
install:
  - go get -v -u github.com/spf13/hugo
env:
  global:
    secure: "TcRLpSmvvWRiaqg9VWdkFdD+XzZx6Oh7wG7KXUCIeLU308MrfmeBXeR4UOUlfZGXRg1ZJePgTXeLGgIY8iWAoi1s+fkL7hjvIIRtjcPlcPc3kmXwFSeFL7zQE+2T7WxDck3AWN2yl17M1FTw69hOX7BRSet4CwNVTjMKrFzb8nh4HMtKzemBxE+4rtBGXfsnuRiFpJUy7KMMUKotMRAmoVnm22ax2zmntbkAOzHtoRBvNNW3EPD3bYUAhMFni///ONrENYfQqtXucTJlfpjXO+JFptF1R1PKBNBpuuBY/FeaIL26F2i2Ps1HnrV1JHbjae3yiFAc1ptH2FsadYG75Sh/wf31EsALjyw18UFp2P+TBhRSY+1P8gPmitMW933oULlO1T4sSoFs5lLeSpYpZ3SwlQNJ01PNrrv5SgPUEcQgfut/YgDdCZ9EBvwYvuBldQRXlpRjiUJO0pf43drq7q5+vyjckRH9iWnlf2TN0DfO2ExO8cVZr+oBotYRMn6dLUCM2EANWxpHORbaIQQTZ2OdmfGl6qEeODAyAStN4+W5S/LgQP0Jjo37LaMeIFMC+O40pLqTP5KjRVK5Wo400A8EZchHHMwroZuSeIRfMNBqp1f6fNsnZlSa4pUty2Mb+yVJuUjPjar3oT2Jnk4pBMIMM1ACJTjiZPKLPBaEB6E="
