sudo: false
language: go
go:
  - 1.5.1
os:
  - linux
before_script:
  - git clone git://github.com/urisavka/blog.git blog
  - git clone git://github.com/urisavka/urisavka.github.io.git urisavka.github.io
  - ln -s `pwd`/urisavka.github.io `pwd`/blog/public
script:
  - cd blog
  - hugo -t hugo-cactus-theme
  - cd ..
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && rev=$(git rev-parse --short HEAD)
  - cd urisavka.github.io
  - git config user.email "urisavka@gmail.com"
  - git config user.name "Yurii Savka"
  - git pull origin master
  - git remote rm origin
  - git remote add origin "https://$GH_TOKEN@github.com/urisavka/urisavka.github.io.git"
  - git add --all
  - git commit -m "rebuild pages at ${rev}"
  - git push origin master
install:
  - go get -v -u github.com/spf13/hugo
