sudo: false
language: go
go:
  - 1.5.1
os:
  - linux
before_script:
  - git clone git://github.com/urisavka/blog.git blog
  - git clone git://github.com/urisavka/urisavka.github.io.git urisavka.github.io
  - ln -s `pwd`/urisavka.github.io `pwd`/blog/public
script:
  - cd blog
  - hugo -t hugo-cactus-theme
  - cd ..
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && rev=$(git rev-parse --short HEAD)
  - cd urisavka.github.io
  - git config user.email "urisavka@gmail.com"
  - git config user.name "Yurii Savka"
  - git pull origin master
  - git remote rm origin
  - git remote add origin "https://$GH_TOKEN@github.com/urisavka/urisavka.github.io.git"
  - git add --all
  - git commit -m "rebuild pages at ${rev}"
  - git push origin master
install:
  - go get -v -u github.com/spf13/hugo
env:
  global:
    secure: "FnAROZIn/Xgzydz5p1ziTBo8yRWWK/Yn9BpSyo1IAKFoSMLkTYk/3Ajx+YxpIq30E0J2tixUqY2jWZXP6WH3EqmcJUMmGulthp4A1PbljktAUnmejymNdfkqUGD34vzs+cPadV5oLCHUfnk1cIpf0PHD0kxrPzl+cIY2LmG7g4yiz9+DPs9a8gHILCVMyKVgV/XYJ83QCkH+C2pTRHwkrjHH775X5lXxMxWS3Zn59ovtyFTY254aFdaOjiurs4pJbdsIm0MswRb/o7L6Gs+fW+8RJBcVVJKUPZj/DmiKvGkZsEWsacvmcS6dNlnmzvby/pVfvHWag16he3JXGDbGchFdtqYjb6HcTKInTbUtb/MP4QdgcJsz4C3wZOcQKJgspknltyxvxTwHWmZ+N/2rBOArkN8mNE0Wp+YHfB8CJBNnMbTWmsFZYASesC6CYrEz193ChVTzsPwktVcgIzC7dFCbgMz14NwwwSC216jYvdDV9xUCwGuhG7VcfCp7kb7IYuKLDo5es73qVAFxR2s7BLAuIlH+Uav1crLeAFhaEHPSaHGvmT/afUvTzkrOCioGV64+fmjV8zNlD8J75GY1hf2gjZNNTd5+CyXER0CIFbhV6oCA/mpFxkYqvyUP2H+WnrS1+x7fdACZj0QeYvfTrh8LY5J8uJQfDW9uNhaGosQ="
